openapi: 3.0.1
info:
  title: Order API
  version: "2.0"
servers:
  - url: "http://localhost:3000"
paths:
  "/products/{id}":
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
        examples:
          GET_DETAILS:
            value: 10
          INVALID_ID:
            value: "344"
          UPDATE_DETAILS:
            value: 10
          DELETE_PRODUCT:
            value: 20
    get:
      summary: Fetch product details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Product"
              examples:
                GET_DETAILS:
                  value:
                    name: "XYZ Phone"
                    type: "gadget"
                    inventory: 10
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Not found"
      operationId: get-product-id
      security:
        - basicAuth: []
    post:
      summary: Update product details
      operationId: post-products-id
      responses:
        "200":
          description: Update successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_DETAILS:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/Product"
            examples:
              UPDATE_DETAILS:
                value:
                  name: "XYZ Fone"
                  type: "gadget"
                  inventory: 10
                  id: 10
      security:
        - oAuth2AuthCode: []
    delete:
      summary: Delete a product
      operationId: delete-products-id
      responses:
        "200":
          description: Deletion successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_PRODUCT:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      security:
        - apiKeyAuth: []
  /products:
    get:
      summary: GET Products based on type
      parameters:
        - name: type
          in: query
          schema:
            type: string
            enum:
              - gadget
              - book
              - food
              - other
      responses:
        "200":
          description: List of products in the response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/Product"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      security:
        - basicAuth: []
    post:
      summary: POST /products
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/ProductDetails"
      responses:
        "200":
          description: POST /products
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/ProductId"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      security:
        - oAuth2AuthCode: []
  /orders:
    get:
      summary: Search for orders
      operationId: get-orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "./common.yaml#/components/schemas/Order"
              examples:
                200_OK:
                  value:
                    - productid: 10
                      count: 2
                      status: "pending"
                      id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      parameters:
        - schema:
            type: integer
          in: query
          name: productid
          examples:
            200_OK:
              value: 10
        - schema:
            type: string
          in: query
          name: status
          examples:
            200_OK:
              value: fulfilled
      description: ""
      security:
        - basicAuth: []
    post:
      summary: POST /orders
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/OrderDetails"
            examples:
              CREATE_ORDER:
                value:
                  productid: 10
                  count: 2
                  status: pending
      responses:
        "200":
          description: POST /orders
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/OrderId"
              examples:
                CREATE_ORDER:
                  value:
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      security:
        - oAuth2AuthCode: []
  "/orders/{id}":
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
        examples:
          DETAILS:
            value: 10
          INVALID_ID:
            value: 433
    get:
      summary: Fetch order details
      tags: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "./common.yaml#/components/schemas/Order"
              examples:
                DETAILS:
                  value:
                    productid: 10
                    count: 2
                    status: "pending"
                    id: 10
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponseBody"
              examples:
                INVALID_ID:
                  value:
                    timestamp: "2023-03-17T12:06:56.177+00:00"
                    status: 404
                    error: "Not Found"
                    message: "Product with id 344 was not found"
      operationId: get-orders-id
      parameters: []
      security:
        - basicAuth: []
    post:
      summary: Update order details
      operationId: post-orders-id
      responses:
        "200":
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                UPDATE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "./common.yaml#/components/schemas/Order"
            examples:
              UPDATE_ORDER:
                value:
                  productid: 10
                  id: 10
                  count: 1
                  status: pending
      security:
        - oAuth2AuthCode: []
    delete:
      summary: Cancel an order
      operationId: delete-orders-id
      responses:
        "200":
          description: Cancel successful
          content:
            text/plain:
              schema:
                type: string
              examples:
                DELETE_ORDER:
                  value: "success"
        "400":
          $ref: "./common_responses.yaml#/components/responses/BadRequest"
      security:
        - apiKeyAuth: []
components:
  schemas:
    ErrorResponseBody:
      properties:
        id:
          type: number
        timestamp:
          type: string
        status:
          type: number
        error:
          type: string
        message:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      description: Basic Authentication with username and password
    oAuth2AuthCode:
      type: oauth2
      description: keycloak based oauth security example
      flows:
        authorizationCode:
          authorizationUrl: http://localhost:8083/realms/specmatic/protocol/openid-connect/auth
          tokenUrl: http://localhost:8083/realms/specmatic/protocol/openid-connect/token
          scopes:
            email: email
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API Key based authentication
